//
// Created by reed on 15.08.21.
//

#ifndef TURBOHIKER_INVINCIBILITYSTAR_H
#define TURBOHIKER_INVINCIBILITYSTAR_H

#include "PowerUp.h"
namespace TH {
class InvincibilityStar : public PowerUp
{

public:
        /**
         * Instantiates an invincibility star at a position + a random offset determined by the EntityMaker
         * @param horizontalOffset: a random offset generated by the EntityMaker
         */
        explicit InvincibilityStar(const float& horizontalOffset);

        /**
         * @return The type of this power up, here "invincibilityStar"
         */
        EntityTypes getType() const override;
};
} // namespace TH

#endif // TURBOHIKER_INVINCIBILITYSTAR_H
